### PR TITLE
Add user-agent to fix auth issues

### LINKED ISSUE #24: Requests blocked by CloudFlare, use User-Agent
Apparently, something about my IP address in combination with the User-Agent used by requests creates an error generated by CloudFlare. When logging in, or doing any other action for that matter, I get a 403 error response with the following content:

```
<!DOCTYPE html>\n<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->\n<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->\n<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->\n<head>\n<title>Attention Required! | Cloudflare</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />\n<!--[if lt IE 9]><link rel="stylesheet" id=\'cf_styles-ie-css\' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->\n<style type="text/css">body{margin:0;padding:0}</style>\n\n\n<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->\n<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><!--<![endif]-->\n\n\n\n</head>\n<body>\n  <div id="cf-wrapper">\n    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>\n    <div id="cf-error-details" class="cf-error-details-wrapper">\n      <div class="cf-wrapper cf-header cf-error-overview">\n        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>\n        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> cp.dyson.com</h2>\n      </div><!-- /.header -->\n\n      <div class="cf-section cf-highlight">\n        <div class="cf-wrapper">\n          <div class="cf-screenshot-container cf-screenshot-full">\n            \n              <span class="cf-no-screenshot error"></span>\n            \n          </div>\n        </div>\n      </div><!-- /.captcha-container -->\n\n      <div class="cf-section cf-wrapper">\n        <div class="cf-columns two">\n          <div class="cf-column">\n            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>\n\n            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n          </div>\n\n          <div class="cf-column">\n            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>\n\n            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n          </div>\n        </div>\n      </div><!-- /.section -->\n\n      <div class="cf-error-footer cf-wrapper">\n  <p>\n    <span class="cf-footer-item">Cloudflare Ray ID: <strong>xxx</strong></span>\n    <span class="cf-footer-separator">&bull;</span>\n    <span class="cf-footer-item"><span>Your IP</span>: xxx</span>\n    <span class="cf-footer-separator">&bull;</span>\n    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>\n    \n    <span class="cf-footer-separator">&bull;</span>\n    <span class="cf-footer-item">\n      <select id="lang-selector">\n        <option value="">Select a Language</option>\n        <option value="en">English</option>\n        <option value="es">Espa\xc3\xb1ol</option>\n      </select>\n    </span>\n    \n  </p>\n</div><!-- /.error-footer -->\n\n\n    </div><!-- /#cf-error-details -->\n  </div><!-- /#cf-wrapper -->\n\n  <script type="text/javascript">\n  window._cf_translation = {};\n  window._cf_translation.locale = \'en\';\n  window._cf_translation.blobs = {};\n</script>\n\n</body>\n</html>\n
```

However, when manually forcing another User-Agent header (``headers={"User-Agent": "foo"}``) this issue is resolved. 

Is it possible to set a User-Agent header on all requests performed by libpurecool so this issue is resolved, even though I'm presumably the only one with this issue.

### PR DESCRIPTION
**Pull request by googanhiem**
Adds a user-agent header, to fix [device list and authentication issue](https://github.com/etheralm/libpurecool/issues/24).

### CODE REVIEW

**Comment by googanhiem** [comment]
I'm a noob, no idea why it failed the test

**Comment by geekofweek** [comment]
It might be more prudent to use a more traditional User Agent, something like the default Android or iOS browser:

`self._headers = {'User-Agent': "Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1"}`

Ideally finding what the app actually sends on either iOS or Android would be best, I wasn't having any luck with Charles proxy trying to determine that.  I fear that something like the Curl user-agent will easily be blocked again.

**Comment by googanhiem** [comment]
Very true, someone needs to get a wireshark instance going and see what the app is using for sure. Like @t04glovern did [here to create a serverless implementation](https://devopstar.com/2019/03/03/dyson-fan-control-over-mqtt-via-serverless).

For the time being this works, and it would be easy to update in future if need be. @etheralm any thoughts?

**Comment by oliverspryn** [comment]
Not 100% sure on this, but I believe this is Android's, for a Nexus 7 (2013) on 6.0.1:

```
Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 7 Build/MOB30X)
```

Charles Proxy

**Comment by KibosJ** [comment]
The app itself seems to use ```DysonLink/29019 CFNetwork/1188 Darwin/20.0.0```

**Comment by oliverspryn** [comment]
Maybe it differs on iOS, since Darwin would most likely not show on Android.

**Comment by KibosJ** [comment]
> Maybe it differs on iOS, since Darwin would most likely not show on Android.

Very true! Using either user-agent should stop Dyson from being able to block it though :)

**Comment by geekofweek** [comment]
@KibosJ agreed, if it's what the app uses it can't be blocked without blocking the app even if that's not the real platform.

**Comment by almostserious** [comment]
https://github.com/home-assistant/core/issues/38607#issuecomment-670686393

`DysonLink/29019 CFNetwork/1188 Darwin/20.0.0`

@KibosJ suggested this user agent from the app

**Comment by googanhiem** [comment]
Updated the user-agent. Give it a test.

**Comment by geekofweek** [comment]
Was already testing that user-agent, looks good though and seems to work fine.

**Comment by SCCMOG** [comment]
> Was already testing that user-agent, looks good though and seems to work fine.

Where abouts is the dyson.py located? I can't see it in the dyson component folder.

**Comment by SCCMOG** [comment]
> > Was already testing that user-agent, looks good though and seems to work fine.
> 
> Where abouts is the dyson.py located? I can't see it in the dyson component folder.

./srv/homeassistant/lib/python3.7/site-packages/libpurecool/dyson.py

**Comment by KibosJ** [comment]
Working fine here now too :)

**Comment by BreBar07** [comment]
Where is the file located on hassio?

**Comment by etheralm** [comment]
Thanks for submitting this PR, don't worry about the tests, I'll sort them out and merge the PR.

**Review by etheralm — APPROVED** [review]

**Pull request merged**
