### PR TITLE
add basic support for dyson pure cool humidify

### PR DESCRIPTION
**Pull request by pfy**
In switzerland, a version of the purecool device with humidify is sold:
https://www.dyson.ch/de-CH/ventilatoren-und-heizlufter/luftreiniger-luftbefeuchter/dyson-pure-humidify-cool/ueberblick.aspx

This MR adds basic support for it (not possible to set the humidify level)

### CODE REVIEW

**Comment by lexijamesesq** [comment]
I just set one of these up (USA version). I can help test support for the device.

**Comment by etheralm** [comment]
Oh thanks, for writing here @alexbussa  I completely missed this PR, I'm sorry. 

I'll have a look at it tomorrow and I'll write some tests that you can run, so that we can gather the info needed to add full support for it.

**Comment by etheralm** [comment]
Guys can you confirm that the fan works with the changes from this PR (apart from the missing functionality). If it does I think that it would be better to merge this and push a new release with preliminary support for it while we work on adding full functionallity for that model.

**Comment by lexijamesesq** [comment]
I can confirm that it allows basic control of of/off, speed, and night mode. 

I’ve noticed...
-  Air quality metrics populate, but don’t update. 
- It’s a single combination HEPA/charcoal filter that loads under the same parameter as HEPA for the other fans. Nothing loads under charcoal.

**Comment by etheralm** [comment]
OK I'll merge this PR and I'll open a ticket where we can continue the discussion.

**Comment by etheralm** [comment]
@pfy thank you for the contribution.

**Pull request merged**
